### ISSUE TITLE
Use xarray/pandas to read/manipulate EK60 data

### ISSUE THREAD

**Issue by erinann** [OSOceanAcoustics/echopype#10]
Currently numpy is used for read/manipulate EK60 data, but it's not as efficient nor convenient to use compared to xarray and pandas.

Task:
  
- [x] Identify functions that need to be changed
- [x] Check variable/attribute naming along with #6 
- [x] Change functions so that the unpacked data are read in as xarray object and directly saved into the netCDF file

**Comment by erinann** [comment]
This was issue number 10 referencing old issue number 4 in OWH18_echopype.

**Comment by leewujung** [comment]
Pull request #18

**Comment by leewujung** [comment]
Closing this issue with PR #18 but anticipating more changes on the netCDF format.
