### ISSUE TITLE
compute_MVBS should propagate and bin average Sv latitude and longitude, and depth/water_level

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#1002]
When the `Sv` input to `commongrid.compute_MVBS` has `latitude` and `longitude` variables (ie, `consolidate.add_latlon` was applied after `compute_Sv`), these variables are currently not maintained in the resulting MVBS dataset. They should be propagated and bin averaged on ping_time.

**Comment by emiliom** [comment]
This issue is being addressed in #1124. Once that PR is merged, this issue can be closed.

**Comment by leewujung** [comment]
This can now be closed!
