### ISSUE TITLE
Change most AZFP Vendor-specific attributes to data variables

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#1055]
Many of the current Vendor-specific group attributes for AZFP can (and should) be changed to data variables. This is something discovered while @lsetiawan was working on #1042. The code changes in #1042 should handle the new data variables without problem, so it is a matter of putting these changes in place.

This is a leftover from #1042.

**Comment by lsetiawan** [comment]
@aniketfadia96 I've assigned you to this, figured this would get you some experience with xarray. Please consult @leewujung for direction. Thanks!

**Comment by aniketfadia96** [comment]
@lsetiawan Okay I'll look into this. Thank you!

**Comment by lsetiawan** [comment]
To let you know about some vocabulary:

AZFP is the instrument type of echosounder and Vendor-specific is a group within the set of datasets. This group is essentially an [xarray dataset object](https://docs.xarray.dev/en/stable/user-guide/data-structures.html#dataset).

These attributes are assigned in https://github.com/OSOceanAcoustics/echopype/blob/main/echopype/convert/set_groups_azfp.py#L329. Currently there are actual data within the attributes of this dataset, but we'd like to make it into `data_vars` or [DataArray objects](https://docs.xarray.dev/en/stable/user-guide/data-structures.html#dataarray) instead.

**Comment by leewujung** [comment]
I'll pick up this issue because we need this for the upcoming release and for generating a CDL for the [sonarnetcdf4-echopype-checker](https://github.com/OSOceanAcoustics/sonarnetcdf4-echopype-checker).

**Comment by aniketfadia96** [comment]
Hey @leewujung @lsetiawan, sorry I couldn't work on this issue. I was occupied with my primary project.

**Comment by leewujung** [comment]
Addressed in #1075 .
