### ISSUE TITLE
Remove deprecated `preprocess` subpackage

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#1076]
When we deprecated the `preprocess` subpackage by moving its functionality into the new `commongrid` and `clean` subpackages (see #889), the plan was to remove `preprocess` with version 0.7.1. Our plan now is to remove it in [0.8.0, which will be released soon](#1063).

Also, we inadvertently left "preprocess" in the [run-test.py](https://github.com/OSOceanAcoustics/echopype/blob/dev/.ci_helpers/run-test.py#L36), which led to running many tests twice! I'll submit a PR shortly to address this.

- [x] Remove "preprocess" from `run-test.py`. Addressed in #1077
- [x] Remove `preprocess` subpackage

**Comment by leewujung** [comment]
This can now be closed!
