### ISSUE TITLE
[File conversion] SUSPECT_CAUSE

### ISSUE THREAD

**Issue by Cristia7** [OSOceanAcoustics/echopype#1086]
### General description of problem
_Required_

### Computing environment
_Required_
- Echopype version:
- How echopype was installed (e.g., conda or pip):
- Operating system:

### Minimum example
_Required: A minimum code snippet that reproduces your problem._
The following code reproduces the errors I encountered:
```python
CODE SNIPPET
```

### Error message printouts
_Required: Copy-paste the entire error messages you encounter here._
Below is the error messages I received when running the above code:
```python
ERROR MESSAGES
```

### Provide an example file
_Required: An example file that allow reproducing the problem._
- Link to an example raw file: SOME_ONLINE_LOCATION. Smaller files are strongly preferred (e.g., <25MB for AZFP and EK60, <100MB for EK80).
- Raw file sensor model: (FOR EXAMPLE: Simrad EK60)

### Troubleshooting
_Optional but preferred: Explain any steps that you have taken to identify the cause of conversion error._

**Comment by leewujung** [comment]
This seems an empty issue. Will close now.
