### ISSUE TITLE
my files don't convert

### ISSUE THREAD

**Issue by Cristia7** [OSOceanAcoustics/echopype#1088]
same file
a part can convert with more ping another part can't with less ping

code as follow
`from echopype import open_raw
import echopype.visualize as epviz
import matplotlib.pyplot as plt

ed = open_raw(raw_file="file_name.raw",sonar_model='EK80')
epviz.create_echogram(ed,vmax=-80, vmin=-200,channel='WBT 738177-15 ES38-7_ES')
plt.show()`
#1087

**Comment by leewujung** [comment]
Closing this as it is a duplicate of #1087.
