### ISSUE TITLE
remove_noise for AZFP data

### ISSUE THREAD

**Issue by jlh5797** [OSOceanAcoustics/echopype#110]
I receive the following error trying to use the remove_noise function with AZFP data: ValueError: conflicting sizes for dimension 'frequency': length 838 on 'range' and length 4 on 'frequency'

I am currently using Echopype version: 0.3.0+2.gd494fd0 but also had this issue using 0.2.0

To reproduce error, please see attached code which is based on code from an echopype jupyter notebook.
[TestNoise2.txt](https://github.com/OSOceanAcoustics/echopype/files/4283935/TestNoise2.txt)

Thanks!

**Comment by leewujung** [comment]
@jlh5797 Thanks for reporting this! It seems that for whatever reason the coordinates are flipped when the backscattering data are saved. We'll look into fixing this soon!
