### ISSUE TITLE
SerializationWarning when saving EK60 xarray variables with dtype=object

### ISSUE THREAD

**Issue by ngkavin** [OSOceanAcoustics/echopype#113]
Some data variables in the beam and NMEA groups for EK60 raise a SerializationWarning when saved. These variables are `channel_id` and `gpt_software_version` in the beam group and `NMEA_datagram ` in the NMEA group.

The full warning: 
`SerializationWarning: variable channel_id has data in the form of a dask array with dtype=object, which means it is being loaded into memory to determine a data type that can be safely stored on disk. To avoid this, coerce this variable to a fixed-size dtype with astype() before saving it.`

**Comment by leewujung** [comment]
@ngkavin : just pinging as you go through all the warnings in Convert.
