### ISSUE TITLE
Error when appending data to a group under a Zarr file

### ISSUE THREAD

**Issue by ngkavin** [OSOceanAcoustics/echopype#114]
Calling `Dataset.to_zarr()` raises a `KeyError` when appending to a .zarr group. This happens when combining raw files into a single Zarr file

**Comment by ngkavin** [comment]
This will likely be fixed in the latest release of xarray as the same [issue](https://github.com/pydata/xarray/issues/3170) has since been merged to xarray.

**Comment by leewujung** [comment]
This will be closed once the branch combine-refactor is merged.
