### ISSUE TITLE
Bump python requirement to python 3.9 and above

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#1144]
## Overview

I've found that xarray has pinned to python >=3.9 since February 2023 as reflected in release [`v2023.02.0`](https://github.com/pydata/xarray/blob/v2023.02.0/setup.cfg#L76). Currently there are failures for Python 3.8 in PR #1124 because it's using xarray version `v2023.01.0` with Pandas > 2. So I think it would be good to bump up the python minimum requirement since we are using xarray heavily.

**Comment by emiliom** [comment]
Makes sense.
