### ISSUE TITLE
`consolidate.add_depth` outputs to work with `compute_MVBS`

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#1152]
In the overhaul of `compute_MVBS` (currently in the working in #1124) the variable `water_depth` is propagated down in the MVBS dataset. We should review what variables are needed to be propagated down, now that we have standardized the z-axis variables in v0.8.0, and some more improvements/refinement of `add_depth` will be introduced soon by @emiliom.

Relevant code section:
https://github.com/lsetiawan/echopype/blob/5a963bd397980583827bac2b6ba0b4bdd6ccf8cc/echopype/commongrid/api.py#L164-L166
This is in the PR code so may change in the future.

**Comment by emiliom** [comment]
Note: the variable that's now propagated is called `water_level`, not `water_depth`.

**Comment by leewujung** [comment]
This will be addressed potentially under #1205 or another PR that addresses the same thing.
