### ISSUE TITLE
xarray/core/duck_array_ops.py RuntimeWarning during casting

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#1155]
In some circumstances which we haven't fully isolated, a warning is emitted by xarray:

... `site-packages/xarray/core/duck_array_ops.py`:188: RuntimeWarning: invalid value encountered in cast `return data.astype(dtype, **kwargs)`

Using a test OOI EK60 file, the warning is triggered by `utils/coding.py:sanitize_dtypes` on `open_raw`, here:

https://github.com/OSOceanAcoustics/echopype/blob/5abca87743ffeb3f5fba0a40f7989ef54c9d1d68/echopype/utils/coding.py#L69-L70

But I  haven't gotten further in identifying the exact variable(s) and condition that lead to it.

This [PR](https://github.com/OSOceanAcoustics/echopype-examples/pull/37) shows echopype-examples notebooks with this warning. See notebooks 2 & 3. The warning occurs on either `open_raw` or `to_zarr`. In [notebook 2 (hake data)](https://osoceanacoustics.github.io/echopype-examples/ms_PacificHake_EK60_cruisetracks.html) it only happens 3 times, which I assume means 3 files out of the total 170 raw files that are handled. 

Originally reported in #1153

**Comment by leewujung** [comment]
This is the same as #1337 and fixed in #1135.
