### ISSUE TITLE
Does `signal.convolve` use dask under the hood?

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#1164]
Within the `ek80_complex` module we use [`signal.convolve`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve.html), which might not be optimized for xarray dataset. Some investigation is needed to see if the code below would properly perform FFT using [dask](https://docs.dask.org/en/stable/) in a parallel fashion.

https://github.com/OSOceanAcoustics/echopype/blob/3ca028f04a4fd3643bb0ad350dc09a699883ee1e/echopype/calibrate/ek80_complex.py#L275-L293

**Comment by lsetiawan** [comment]
Look into potentially using: https://xrft.readthedocs.io/en/latest/

**Comment by anantmittal** [comment]
Confirm if there is a test function for `compress_pulse` function in `echopype/echopype/calibrate/ek80_complex.py`.

**Comment by lsetiawan** [comment]
@anantmittal You should be able to use the same test data like in the `test_ek80_BB_power_Sv` test: https://github.com/OSOceanAcoustics/echopype/blob/9dfe5ba9cd656eb2f5dc9007fcb960231108cf1e/echopype/tests/calibrate/test_calibrate_ek80.py#L155-L156

**Comment by leewujung** [comment]
Addressed by #1208.
