### ISSUE TITLE
Check to see if this masking `xr.where` parallelize

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#1165]
This [`xr.where`](https://docs.xarray.dev/en/stable/generated/xarray.where.html) needs to be investigated to see if it can parallelize with the use of dask.

https://github.com/OSOceanAcoustics/echopype/blob/3ca028f04a4fd3643bb0ad350dc09a699883ee1e/echopype/mask/api.py#L500

**Comment by anantmittal** [comment]
Command to run the tests and capture the stdout:
`python .ci_helpers/run-test.py --local --pytest-args="-vvrP" echopype/mask/api.py`

**Comment by leewujung** [comment]
@lsetiawan : the code you pointed to above was actually not the one we were discussing 😬

Below are the 2 potential places where the calibration code (`compute_Sv`) code can have bottleneck:

- in `get_vend_cal_params_power` where a broadcasting is probably used to get a data variable into the "right" shape based on indexing:
https://github.com/OSOceanAcoustics/echopype/blob/593a7e173dffd34858a7587cf2f31633a23a841c/echopype/calibrate/cal_params.py#L299-L304

- in `harmonize_env_param_time` where there is either a check for all the timestamps or an interpolation:
https://github.com/OSOceanAcoustics/echopype/blob/593a7e173dffd34858a7587cf2f31633a23a841c/echopype/calibrate/env_params.py#L53-L66

**Comment by leewujung** [comment]
I'll close this now, since my comment above is replicated in #1200.
