### ISSUE TITLE
Add `depth` to allowed dimension in `apply_mask`

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#1204]
Right now `mask.apply_mask` only allows datasets with `range_sample` as one of the dimensions along with `ping_time` and `channel` (optional). However outputs of `compute_MVBS` for example would have dimension `depth` in place of `range_sample` in the along-range dimension. We need to add `depth` into the allowed dimension in `apply_mask`.

**Comment by ctuguinay** [comment]
Closed with the merging of https://github.com/OSOceanAcoustics/echopype/pull/1230
