### ISSUE TITLE
Improve `estimate_noise` binning routine

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#1211]
## Overview

This issue follows up on Issue https://github.com/OSOceanAcoustics/echopype/issues/1028. Improvements in 2D binning routines have been implemented for both `compute_MVBS` and `compute_NASC`, however it may seem that `estimate_noise` is still left as mentioned in the issue. 

https://github.com/OSOceanAcoustics/echopype/blob/f98e825e808a98dfdf43f66c8be242347d353e3b/echopype/clean/noise_est.py#L53-L81

An investigation and improvements needs to happen for this method to enhance efficiency, memory usage, and robustness against different types of data.

**Original description by @leewujung can be found at https://github.com/OSOceanAcoustics/echopype/issues/1028#issue-1662507356.**

**Comment by MohamedNasser8** [comment]
Hello @lsetiawan,
As I understand it, `ping_time` can refer to actual timestamps or simply be a sequence of indices. We need to account for both scenarios: when `ping_time` represents real-time data and when it represents indices. I am making sure to handle both cases appropriately to ensure accurate results.

**Comment by ctuguinay** [comment]
Closing this as coarsen itself is very fast and probably does not need the Flox algorithms to speed up this process.
