### ISSUE TITLE
Overhaul AZFP Environnment group

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#1225]
Currently the AZFP `Environment` group is created with `temperature` and `pressure` variables, even if the variables have no valid data. Since `pressure` data are almost never present, and these variables are not defined by SONAR-netCDF4, always creating these variables is unnecessary and wasteful.

Also, the mandatory variables `absorption_indicative` and `sound_speed_indicative` are not created.

- [ ] Always create `absorption_indicative` and `sound_speed_indicative` variables (float type). In SONAR-netCDF4 they have a `frequency` dimension; here, they will have a `channel` dimension. At this time I don't know where the values would come from, so set to them to `np.nan`
- [ ] Create an associated `frequency_nominal(channel)` variable
- [ ] `temperature` will be created only if `self.parser_obj.unpacked_data["temperature"]` contains valid data
- [ ] `pressure` will be created only if `self.parser_obj.unpacked_data["pressure"]` contains valid data

The attributes for `absorption_indicative` and `sound_speed_indicative` are taken from the convention:

```python
# absorption_indicative
{
    "long_name": "Indicative acoustic absorption",
    "units": "dB/m",
    "valid_min": 0.0,
}
# sound_speed_indicative
{
    "long_name": "Indicative sound speed",
    "standard_name": "speed_of_sound_in_sea_water",
    "units": "m/s",
    "valid_min": 0.0,
}
````

Note that if neither  `temperature` nor `pressure` contain valid data, the variables won't be created, and the `time` dimension and coordinate variable should not be created either.

**Comment by leewujung** [comment]
This can be closed now since #1226 is merged.
