### ISSUE TITLE
Conda-forge build issue for v0.3.1

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#127]
@ocefpaf : Just wanted to ping you here so it gets into your queue. Thanks in advance! :)

conda-forge/echopype-feedstock#4 The feedstock complains about no module named zarr (here) for the most recent release 0.3.1, but I am not sure where to specify that outside of requirements.txt and environment.yml

Any guidance will be really helpful!!

**Comment by emiliom** [comment]
Looks like you can close this issue now!

**Comment by leewujung** [comment]
Yes! 😺  I'll update README and docs in a bit.
