### ISSUE TITLE
RAW data parser (for ek80 code)

### ISSUE THREAD

**Issue by emma-ozanich** [OSOceanAcoustics/echopype#13]

**Comment by leewujung** [comment]
Almost there! 😎

@ngkavin I am noting the below items here for us to keep track of things:
- Currently ping time is saved as float64 but should be datetime64.
- Split-beam angle data for CW mode EK80 files are not currently saved. Note can reference EK60 data handling of this.

**Comment by leewujung** [comment]
Update: the above is being addressed in the combine-refactor branch.
