### ISSUE TITLE
Add additional `Sv_offset` values to AZFP calibration

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#1300]
From communication with Steve Pearce at ASL Env Science, we can now add the following `Sv_offset` values for calibrating AZFP data.
- 67 kHz: 500 us (1.1 dB)
- 125 kHz: 150 us (1.4 dB), 250 us (1.3 dB)
- 200 kHz: 150 us (1.4 dB), 250 us (1.3 dB)
- 455 kHz: 250 us (1.3 dB)
- 769 kHz: 150 us (1.4 dB)

**Comment by ctuguinay** [comment]
Closed by #1304
