### ISSUE TITLE
Enable Start to End Lazy Loaded / Delayed Computation for `compute_Sv`

### ISSUE THREAD

**Issue by ctuguinay** [OSOceanAcoustics/echopype#1312]
From the conversation regarding the merged PR #1302, it's clear that a user cannot run a fully delayed `compute_Sv` on EK80 Broadband Complex data, and having a fully delayed `compute_Sv` would be very nice since it allows further scalability.

The following tasks are needed to make this happen:
- [x] Check the status of EK60 and EK80 CW data calibration: Can they be done fully delayed? If they cannot, identify and fix any forced computation.
- [x] Look into #1212. This is delayed computation, but memory leaks.
- [x] Modify `compress_pulse` to not have any `.compute()`. Might be as simple as just not calling it.

I'm leaving this as 1 issue to be done for Milestone 0.9.0, but this can be done in separate PRs and different milestones if it becomes too much for one PR, which it probably will.

**Comment by leewujung** [comment]
#1311 addresses the last point. It also includes other components required to handle lazy-loaded `EchoData` object for calibrating broadband complex data.

**Comment by ctuguinay** [comment]
Closed by merging of #1311 and #1331
