### ISSUE TITLE
`apply_mask` does not interpret `NaN` correctly

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#1375]
Apparently right now `echopype.mask.apply_mask` does not interpret `NaN` as 0 or `False` in the mask production, and actually treats it as 1 or `True`. 

This is because `xr.where` treat `NaN` in _cond_ as `True`... kinda unexpected behavior.

I'll follow up with a PR to fix this.

**Comment by ctuguinay** [comment]
Closed by merging of #1376
