### ISSUE TITLE
Remove analysis subpackage, for now

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#149]
The [analysis](https://github.com/OSOceanAcoustics/echopype/tree/convert-refactor/echopype/analysis) subpackage is just an empty placeholder at this time, at least in both master and the convert-refactor branches. It hasn't been touched in 16 months. Given that there's already plenty of changes in place for a new release, it seems unlikely (and unwise?) that you'll be fleshing out `analysis` for this release. To a user, I think it's confusing and misleading to have it there. I suggest removing it until you're actually ready to add that functionality.

**Comment by leewujung** [comment]
This sounds good. I'll remove it when merging the `convert-refactor` branch for the new release.

**Comment by leewujung** [comment]
This is closed by #160.
