### ISSUE TITLE
echopype logo

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#152]
Any thoughts on this logo, other than it looks like the pipe under sink? 🤪

<img src="https://user-images.githubusercontent.com/15334215/83816322-238a7780-a690-11ea-8a10-bb8e46c04cf8.png" alt="alt text" width="200">

**Comment by lsetiawan** [comment]
This is a great logo IMO :+1:

**Comment by cyrf0006** [comment]
Looks good!

**Comment by leewujung** [comment]
Added to docs and README! 😀
