### ISSUE TITLE
Handle missing GPS and/or MRU data

### ISSUE THREAD

**Issue by ngkavin** [OSOceanAcoustics/echopype#185]
For some EK80 data files, pitch, roll, heave, and NMEA data are not recorded, so they are saved as empty lists. When creating an xarray dataset, pitch, roll, heave, lat, and lon are assumed to have coordinates of time, so an error is raised when these values are empty.

The best solution is likely to fill empty pitch, roll, heave, lat, and lon values with NaNs with length of ping_time so that it can be saved to the xarray dataset.

**Comment by leewujung** [comment]
Ugh, upon digging into the code some more, I found a bug 😎

Under the MRU datagram ([here](https://github.com/OSOceanAcoustics/echopype/blob/master/echopype/convert/ek80.py#L133))
`self.mru_data['timestamp']` records the actual MRU timestamp
but when saving to platform group, we currently have 
`out_dict['ping_time'] = self.ping_time` 
which is the ping time from the RAW datagram (echo data) ([here](https://github.com/OSOceanAcoustics/echopype/blob/master/echopype/convert/ek80.py#L266)).

Lat/lon have another time base from the NME datagram and that timestamp is now correctly saved into the Platform group.
