### ISSUE TITLE
Add NMEA message type as another data variable in Platform group

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#232]
Currently EK data are default to only save the GGA NMEA messages in the Platform group. It will be better to save _all_ messages and include the message type as another data variable. See #231 for discussion.

**Comment by emiliom** [comment]
I don't know anything about the different NMEA messages, what each of them means, or why they have different resolutions. So, I don't know whether the best default is to save only GGA vs all messages (*). But adding a NMEA-GPS-message-type variable is a good idea independently of what the default it. Plus, I also like the current functionality that gives users the choice of what message types to save.

(*) Actually, I take it back! From the perspective of a lossless conversion from raw to netcdf/zarr format, it's best to have the default include all data.

**Comment by leewujung** [comment]
This can now be closed now that `class-redesign` is merged to `master`. :D
