### ISSUE TITLE
Raw files with repeated ping times raises error while converting

### ISSUE THREAD

**Issue by ngkavin** [OSOceanAcoustics/echopype#235]
If a ping is duplicated in the raw file, an error is thrown when trying convert. Specifically, when merging datasets along the frequency dimension like in  `set_env` of `SetGroupsEK60`.
The following error is raised: `ValueError: cannot reindex or align along dimension 'ping_time' because the index has duplicate values`

This issue is mentioned here https://github.com/pydata/xarray/issues/2108
An example EK60 raw file that produces this error can be found here: https://rawdata.oceanobservatories.org/files/CE02SHBP/MJ01C/07-ZPLSCB101/2019/12/01/CE02SHBP-MJ01C-07-ZPLSCB101_OOI-D20191201-T000000.raw

**Comment by imranmaj** [comment]
Potential solutions:

- Throw out duplicates
- Increment duplicates by smallest possible time amounts (e.g., 1 ns, 1 ms)

**Comment by imranmaj** [comment]
Fixed in https://github.com/OSOceanAcoustics/echopype/pull/433
