### ISSUE TITLE
remove file download code from test_convert.py?

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#264]
In [echopype/tests/test_convert.py](https://github.com/OSOceanAcoustics/echopype/blob/class-redesign/echopype/tests/test_convert.py), [_download_file()](https://github.com/OSOceanAcoustics/echopype/blob/class-redesign/echopype/tests/test_convert.py#L55) and [download_files()](https://github.com/OSOceanAcoustics/echopype/blob/class-redesign/echopype/tests/test_convert.py#L95) are no longer used now that the test data files are all staged via Google Drive + rclone + Docker. Should this "download" code be removed?

**Comment by leewujung** [comment]
@emiliom : just wanted to ping to bring this back to the foreground again now that we have a cleaned-up `master` branch and all tests are running. Thanks!

**Comment by emiliom** [comment]
As far as I can tell from inspecting both the [test_convert.py code](https://github.com/OSOceanAcoustics/echopype/blob/master/echopype/tests/test_convert.py) and the log it generates, [download_files()](https://github.com/OSOceanAcoustics/echopype/blob/master/echopype/tests/test_convert.py#L95) (and hence `_download_file()) is not used. And I don't really see a scenario where we would use it, or something we actually want to test for involving that code. So, I vote to remove it.

@lsetiawan what do you think? If you agree, I can submit a PR.

**Comment by emiliom** [comment]
Hey @lsetiawan, could you confirm what I said above :point_up_2: about `download_files()` and `_download_file()`?
