### ISSUE TITLE
LFS Issue

### ISSUE THREAD

**Issue by DLWangSan** [OSOceanAcoustics/echopype#268]
can not download your test files with LFS. Following is the log file, could you take a look please?
```
$ git-lfs.exe filter-process
Error downloading object: echopype/test_data/azfp/17031001.01A (32173cb): Smudge error: Error downloading echopype/test_data/azfp/17031001.01A (32173cb43dd6f10f9e33d3362edd36909409ffa9a3c4ad5111514ffc2906c381): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response
...
```

**Comment by leewujung** [comment]
@DLWangSan : We are moving away from using LFS for storing the test data due to the cost associated with the bandwidth usage from reading EK80 test files. We are setting up another location for the test files in the upcoming release and will keep you posted when the release is out.

**Comment by DLWangSan** [comment]
thanks！

**Comment by emiliom** [comment]
@leewujung can we close this issue and keep track of the Git LFS deprecation in #271?

**Comment by leewujung** [comment]
Yes that's a good idea. I'll close this here.
