### ISSUE TITLE
Conforming to data convention definition ncml

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#283]
Recently, I came across this: https://github.com/ices-publications/SONAR-netCDF4/blob/master/docs/convention_definition.ncml, which is a data convention definition for SONAR-netCDF4. It would be great for echopype to be able to read this and check against it and get the proper attributes/variables in creating a standardized file. 

@emiliom Any suggestion on tools to read this ncml file into code?

**Comment by emiliom** [comment]
I'll reply to this in #210

**Comment by lsetiawan** [comment]
Closing. Further discussion can be found in #210.
