### ISSUE TITLE
Compliance of frequency variable encoding in converted files

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#307]
### Original

It appears that `frequency` has been encoded in `int32` for AZFP converted files, which results into errors when computing for environmental variables #304 . Let's fix this by encoding it as `float` as specified in the convention.

### Updated

Per @emiliom 's comments below, let's expand the scope of this issue beyond AZFP, so that we do not forget about this other side of compliance issue in conjunction with #210 .

**Comment by leewujung** [comment]
Closed by #309 .

**Comment by emiliom** [comment]
The same change will have to be made for the other sensor types (EK60, etc), right? How about expanding the scope of this issue (and reopening it) beyond AZFP, so the others are not forgotten?

**Comment by leewujung** [comment]
Yes I was gonna add a comment in the convention issue. We can reopen this issue and do everything here. :)

**Comment by leewujung** [comment]
I think we can probably make this in a minor release v0.6.X once we have the main (breaking) things down.

**Comment by emiliom** [comment]
The change to float was done for AZFP in PR #309 (originally to the old `frequency` variable).

For EK60 and EK80, `frequency_nominal` is already set to float, too. 

I think we can close this issue.

**Comment by leewujung** [comment]
Sound good. I imagine this will be covered by #1043

**Comment by emiliom** [comment]
Thanks. Yeah, the goal in #1043 is to also check for data types.

I'll close this issue now.
