### ISSUE TITLE
Error when trying to calibrate an EK80 file with both CW and BB channels

### ISSUE THREAD

**Issue by ngkavin** [OSOceanAcoustics/echopype#310]
Calibration fails for the test file `Summer2018--D20180905-T033113.raw` when the calibration parameters are being retrieved. The error message is: `ValueError: operands could not be broadcast together with shapes (5,5) (3,1)`. 

Specifying the waveform_mode and the encode_mode still resulted in the error.

**Comment by leewujung** [comment]
This is due to the fact that `_get_vend_cal_params_power` should not be called in the BB case, and the factors 'sa_correction', 'gain_correction' are not used for BB calibration. This requires some refactoring and let's try to get this in in the upcoming minor releases.

**Comment by imranmaj** [comment]
Fixed in #400
