### ISSUE TITLE
Continuous Integration PR run need some option to be able to run all tests

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#357]
Right now the selective tests can be problematic for changes that effects multiple modules and it doesn't give an accurate depiction of the overall tests. If the CI can run all tests when the PR is labeled to do so, this will help to ensure that we don't miss anything.

**Comment by lsetiawan** [comment]
There is now a label `Needs complete testing` for this.

**Comment by leewujung** [comment]
It's awesome that this can be done using a label! 🎉
