### ISSUE TITLE
Move CI_test_data Google Drive folder to echopype Google Drive

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#358]
@lsetiawan please move the `CI_test_data` Google Drive folder from your personal drive to the `echopype` Google Drive, and update the CI as needed to point to that folder. Thanks!

**Comment by lsetiawan** [comment]
I changed the `TEST_DATA_FOLDER_ID` secrets to the new folder ID that link to the `CI_test_data` folder in `echopype` team drive. I re-ran the docker build CI and it successfully built with the new ID: https://github.com/OSOceanAcoustics/echopype/runs/2641045943?check_suite_focus=true

**Comment by emiliom** [comment]
Thank you!!
