### ISSUE TITLE
Conversion improvements for AD2CP files

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#360]
Let's use this issue to note down the various things to improve for the AD2CP file conversion. The issue text will continue to be updated.

Note that a lot of these are related to what encoding convention we'd follow since there are _a lot of_ ad-hoc addition to the current convention and that needs to be reviewed also.

### Overall
- many data variables have missing attributes: many of those still need to be defined by the convention, but should at least have the physical units

### Different groups
- `Sonar` group 
   - this group is currently empty but should be encoded
- `Beam_complex` group:
   - `echosounder_raw_transmit_samples_r|i` has the same `ping_time` dimension with NaNs padded to the same dimension as `echosounder_raw_transmit_samples_r|i`, because the transmit samples only contains 1 ping. Since there is a separate `time_echosounder_raw_transmit` coordinate, this NaN padding shouldn't happen?
- `Beam` group:
   - `amplitude_echosounder` is empty for data in Echosounder mode, but there is an additional variable `echosounder` that contains values that look like the Echosounder mode recording. However, there are weird spikes in the data that are not there when compared with OceanContour outputs like below:
   - ![Screen Shot 2021-05-19 at 10 31 26 PM](https://user-images.githubusercontent.com/15334215/118924549-1ba00380-b8f2-11eb-88e1-2b95a062289d.png)

**Comment by leewujung** [comment]
@imranmaj : tagging you on this. Let's make a plan to fix these once we pick up the more immediate leftovers from v0.5.0.

**Comment by imranmaj** [comment]
Spikes occur because data was being parsed as unsigned integers in accordance with the specification, but they should actually be parsed as signed integers

**Comment by leewujung** [comment]
These issues are addressed by #388.
