### ISSUE TITLE
Combine multiple EchoData objects

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#364]
Right now we have `open_raw` that handles parsing raw data from a single file into a nice `EchoData` object. Let's revamp the previous `combine=True` option so that we can combine multiple `EchoData` objects explicitly. This function can then be used under the hood for when we put together an `open_mfraw` function.

Notes from #180 for Environment group:
- For EK60: these parameters are encoded with each ping (each sample datagram)
- For EK80: these parameters are encoded with a single ping_time before all sample datagrams
- For AZFP: temperature and pressure of the instrument is recorded with each ping, but not salinity, which has to be supplied by the user during calibration.

**Comment by imranmaj** [comment]
Implemented in #383, #414, #422
