### ISSUE TITLE
Need docs on using pre-commit for contributors

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#368]
@emiliom could you create some docs for contributors to be able to use `pre-commit`? Thanks!

**Comment by emiliom** [comment]
Sure. But can you add a bit of information here about what it encompasses, exactly? I'm not confident I'm in the best position to describe it, but I can take run with it if you give me a starting point.

**Comment by lsetiawan** [comment]
So, `pre-commit` is actually in `requirements-dev.txt`, a contributor would install all those packages there. Once all of that are installed. They should run `pre-commit install` before all the docker services deployment and stuff like that. This way, everytime they make changes to the code and try to commit, pre-commit runs and adjusts as needed before they can actually commit changes. If they want to manually run `pre-commit` before actually doing git commit, then they can also do `pre-commit run --all-files`. Here's a link to the pre-commit docs: https://pre-commit.com/#usage. Thanks @emiliom  😄

**Comment by emiliom** [comment]
Thanks!

**Comment by emiliom** [comment]
I've moved this issue to the 0.5.2 milestone. It'll be part of a larger batch of "contributing" doc updates that I'll work towards releasing to live (readthedocs `stable`) incrementally rather than with code releases.

**Comment by emiliom** [comment]
Addressed by #417
