### ISSUE TITLE
Saving original ping_time after EK60 ping_time reversal correction

### ISSUE THREAD

**Issue by imranmaj** [OSOceanAcoustics/echopype#394]
# Summary

EK60 `ping_time` values are occasionally non-monotonical, and can sometimes decrease before continuing to increase. #297 introduced a function to correct this by finding some nth `ping_time` which occurs chronologically before the n-1th `ping_time` and increasing `ping_time`s n and afterward by a constant amount. #383 uses the function when combining `EchoData` objects. However, Echopype users may want to view or use the original non-monotonical `ping_time` values (which will be referred to as the "pre-correction `ping_time`"), so Echopype should provide a way to access the pre-correction `ping_time` in addition to performing the correction.

`ping_time` values after the correction will be referred to as the "post-correction `ping_time`".

# Possible Solutions

- Store the entire pre-correction `ping_time` in a data variable, probably in the provenance group
    - This is the current approach taken by #383 
    - Disadvantage: This may bloat the dataset in cases where the `ping_time` array is very large
- Store time values where corrections occur and the amount of shift that was applied in the correction in a dictionary in the form `{ time: shift amount }`
    - Disadvantage: This information should preferably be stored in format which conveys a sense of ordering so that users can traverse the post-correction `ping_time` in order and revert the shifts to obtain the pre-correction `ping_time`
- Store time values where corrections occur and the amount of shift that was applied in the correction in a list of tuples in the form `[(time, shift amount)]`
    - This solves the issue of shifts being unordered from the previous solution
    - Disadvantage: This may be confusing to users because it is not immediately clear whether the `time` values in this format come from the pre-correction `ping_time` or the post-correction `ping_time`
- Store **indexes** of time values where corrections occur and the amount of shift that was applied in the correction in a list of tuples in the form `[(time index, shift amount)]`
    - This removes confusion of time values being from either pre-correction `ping_time` or post-correction `ping_time`s; a time index will reference both a pre-correction `ping_time` value and its corresponding post-correction `ping_time` value

# Other Questions

- Should Echopype provide an option to disable the `ping_time` correction entirely?

**Comment by leewujung** [comment]
This was addressed by #383 #425 #433.
