### ISSUE TITLE
Using open_raw for AZFP data files with name other than .01A 

### ISSUE THREAD

**Issue by Linda189** [OSOceanAcoustics/echopype#418]
We can convert AZFP data files using open_raw for the .01A file. However, not all AZFP data files are .01A files. There are 2 parts that the filename can change (the number and letter of the file)
1. The number: 
When we collect data with multiple phases (max 12 phases) in one deployment, the data files will format as .01A (for phase 1), .02A(for phase 2),... So the AZFP file name could be from .01A to .12A
2. The letter:
When we deploy the instrument multiple times in one hour, the data files name will be ascending in alphabetical order each time it's deployed, which the file name could be from .01A to .01Z. 

![image](https://user-images.githubusercontent.com/72575070/129432079-1b1c72c1-68dc-4155-968c-d415cd5b1d96.png)

![image](https://user-images.githubusercontent.com/72575070/129432111-5fb7eb22-1d9d-4faa-addd-11b2a7cc3894.png)

@leewujung @imranmaj hope you can fix this problem. Let me know if you need more information about the AZFP files.

**Comment by imranmaj** [comment]
Fixed in #428
