### ISSUE TITLE
xarray requirements

### ISSUE THREAD

**Issue by mbdunn** [OSOceanAcoustics/echopype#426]
When installing echopype the xarray package that is automatically downloaded is v.0.16 but needs to be v0.17+ to avoid errors with combine-attrs.

**Comment by emiliom** [comment]
@mbdunn we're aware of this issue and have implemented a fix. We're wrapping up a new release (0.5.3) that should be out within a few days (@leewujung can confirm this!), and in that release the xarray version installed should be the latest stable version -- currently 0.19.0. Stay tuned!

**Comment by leewujung** [comment]
Yes! Once we get 0.5.3 released -- should be very soon, we are just waiting for a small docstring fix -- this should be good. If you want to get that now, feel free to pull the `dev` branch since that particular PR (which unpinned versions of all dependencies) is already merged and functional.

**Comment by mbdunn** [comment]
Awesome! Great that it is already taken care of. I'll close the issue :)
