### ISSUE TITLE
Change both CI actions flags to be based on PR titles

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#452]
[Currently](https://echopype.readthedocs.io/en/stable/contributing.html#continuous-integration-github-actions), the CI can be skipped via the commit string "[skip ci]", and the PR label `Needs Complete Testing` is used to force the running of all CI tests.

For consistent usage and convenience, change this so that both are implemented as PR title strings: "[skip ci]" and "[all tests ci]".

From @lsetiawan: Looks like there's a "title" value that I can grab and check, https://docs.github.com/en/rest/reference/pulls

**Comment by emiliom** [comment]
Once this is implemented (maybe soon after 0.5.5 release?), let's remember to update the docs, https://echopype.readthedocs.io/en/stable/contributing.html#continuous-integration-github-actions

**Comment by emiliom** [comment]
@lsetiawan I believe this isn't implemented yet, right? Would it be easy to add in the near term?

**Comment by lsetiawan** [comment]
It's not implemented yet. Sorry I missed this issue previously. I think that can be added soon. I'll take a look. Thanks for putting it in my radar again.

**Comment by emiliom** [comment]
> Sorry I missed this issue previously. 

No worries! We have a lot to keep track of and prioritize.

> I think that can be added soon. I'll take a look. Thanks for putting it in my radar again.

Awesome. Thanks!

**Comment by emiliom** [comment]
This change has been implemented (PR #721). But let's leave this issue open for now as a reminder to [update the documentation](https://echopype.readthedocs.io/en/stable/contributing.html#continuous-integration-github-actions)

**Comment by emiliom** [comment]
We're now tracking the update to the documentation in #757. Closing
