### ISSUE TITLE
Preprocess module does not have tests against "real" data.

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#454]
Currently, the preprocess module is not tested against any "real" data. Tests against toy data can be found at https://github.com/OSOceanAcoustics/echopype/blob/main/echopype/tests/old/test_preprocess.py.

**Comment by leewujung** [comment]
It is kinda bizarre that `test_preprocess.py` is under `tests/old`! 
Shouldn't it be under `tests/preprocess`? 
I guess this calls for a PR to both add tests running on real data and fix the folder structure.
