### ISSUE TITLE
Provide control over echopype's output to the terminal

### ISSUE THREAD

**Issue by gavinmacaulay** [OSOceanAcoustics/echopype#457]
echopype outputs text when doing stuff, such as:

`15:40:36  parsing file D20180619-T183100.raw, time of first ping: 2018-Jun-19 18:31:00`

This can be distracting when using echopype, especially when it is used as part of a separate program. It would be useful if this could be turned off, or perhaps controlled using Python's logging functionality.

**Comment by emiliom** [comment]
This need was recently brought up again in #722 (now closed to shift the discussions here). @cornejotux will try to tackle it :pray:

**Comment by emiliom** [comment]
Implemented in PR #772. Closing.
