### ISSUE TITLE
Clip external platform data to ping_time range when using update_platform; and change time2 to location_time

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#460]
The external platform data passed to `echodata.update_platform` may span a time range greater than the one in the echodata object being operated on. Currently, all the external data will be added ([echodata/echodata.py#L319](https://github.com/OSOceanAcoustics/echopype/blob/dev/echopype/echodata/echodata.py#L319)). I think the "extra data" is unnecessary and potentially confusing. I suggest that it'd be best to clip the time range of the external platform data based on the time range in the beam `ping_time`

**Comment by emiliom** [comment]
Done in #476:

> change time2 to location_time so that we are consistent before our convention adherence overhaul.
> Clip external platform data to ping_time range when using update_platform.

Remaining tasks:
- expand the clipped range of `extra_platform_data` to be 1 index before and 1 index after the time period spanned by `ping_time`, so that the first and last `ping_time` has something to interpolate lat/lon to.
- add a test for the time ranges?
- ensure that the `location_time` attributes and encodings that have been added (see #476#pullrequestreview-800621745) are saved into the netcdf file (and zarr?) when exporting via `to_netcdf`

**Comment by leewujung** [comment]
Oops I only see this now and have opened up a new issue #485 to track the first 2 tasks. 
But it seems better to have new issues instead of overloading this one? 
I am fine going either way.

Just copying my comment at the bottom of #476 here if we decide to just continue using this one:
> One thing I think we should consider is to add tests specifically for the attributes and encodings at the end of various operations, especially those that "touch" the organized Datasets in the groups. The ones I can think of now are combine_echodata, update_platform, read from results of to_netcdf/zarr.

**Comment by emiliom** [comment]
This issue started out focusing on the time range clipping, but its scope was creeping. #485 is focused on that original scope. Let's close this issue (as replaced by #485) and I'll open a new one focused on:

> 3. ensure that the `location_time` attributes and encodings that have been added (see [#476](https://github.com/OSOceanAcoustics/echopype/pull/476#pullrequestreview-800621745)) are saved into the netcdf file (and zarr?) when exporting via `to_netcdf`. See the status update [here](https://github.com/OSOceanAcoustics/echopype/pull/476#issuecomment-965661370)
> 
> Additional note: I think there's some linkage between the 3rd of these tasks and #479

**Comment by emiliom** [comment]
Continued in #488
