### ISSUE TITLE
sonar_model for ad2cp data?

### ISSUE THREAD

**Issue by gcutt** [OSOceanAcoustics/echopype#461]
What are the options for the sonar_model argument in open_raw? Which string should be used for Nortek ad2cp data? 
Can I use any string, such as 'ntk', for example, 
ed = open_raw('FILENAME.ad2cp',  sonar_model='ntk') 
?

**Comment by leewujung** [comment]
The current docs in `stable` is updated with info up to v0.5.4.

Let's keep this open so that we will remember to add support for ES70 and ES80 from #409 once v0.5.5 is out.

**Comment by emiliom** [comment]
And also let's remember to add such support to the `open_raw` doc string in the `dev` branch.

**Comment by leewujung** [comment]
This can be closed once `dev` in merged to `main`.

**Comment by leewujung** [comment]
Closing this now to reduce clutter.
