### ISSUE TITLE
Document optional parameters for calibration functions

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#463]
Currently parameters `waveform_mode` and `encode_mode` for calibration EK80 data are not documented. We should add them in in the not very distant future, especially since we're now diving back in to make sure everything is done correctly.

**Comment by emiliom** [comment]
@leewujung can we close this issue now that #477 is merged?

**Comment by leewujung** [comment]
Sounds good. Closing this now.
