### ISSUE TITLE
Zenodo badge leads to a very old version (0.4.1).

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#469]
The current zenodo DOI leads to a very old version of 0.4.1. Rather than the latest 0.5.4. This needs to be changed. Echopype does have a `concept doi` that leads to the latest version of the software everytime. Maybe we can use that instead, or create a way to update the zenodo badge at each release.

**Zenodo Concept DOI**

<a href="https://doi.org/10.5281/zenodo.3906999">
    <img src="https://zenodo.org/badge/doi/10.5281/zenodo.3906999.svg" alt="DOI">
</a>

**Comment by leewujung** [comment]
Oh I didn't realize that it's not linked to the general DOI. Yes I think using that would work. I'll do a PR. Thanks for noticing it! 😄

**Comment by leewujung** [comment]
This is again addressed by #473 .

**Comment by leewujung** [comment]
Let's close this now to reduce clutter. :)
