### ISSUE TITLE
Consolidate definition and use of `DEFAULT_CHUNK_SIZE`

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#484]
`DEFAULT_CHUNK_SIZE` is curiously declared in two different places: `echopype/convert/set_groups_base.py` and `echopype/convert/api.py`. 

It is only used in 1 place for single file handling (`SetGroupsEK60.set_platform`) and does not seem to be used in any other places (!)

Strangely (but nicely), it is used in `convert_combine.perform_combination` which is used by `ep.combine_echodata`.

These should be resolved when we move to more performance-related work.

**Comment by b-reyes** [comment]
@leewujung I did a quick search and we are not really using `DEFAULT_CHUNK_SIZE` anymore. It is used in a couple of spots, but they are currently commented out. Also, it is still defined in two places. I do not plan on using this in `combine_echodata`.

**Comment by leewujung** [comment]
So we can just remove this completely then?

**Comment by emiliom** [comment]
Looks like we should

**Comment by b-reyes** [comment]
> So we can just remove this completely then?

If you are asking if we can remove `DEFAULT_CHUNK_SIZE`, then yes. We can definitely remove this.

**Comment by leewujung** [comment]
Yes. Could you please submit a PR to remove that? Thanks!

**Comment by b-reyes** [comment]
In PR #848 we have removed `DEFAULT_CHUNK_SIZE`, so this issue is no longer necessary. I will go ahead and close it.
