### ISSUE TITLE
roll is both method and DataArray

### ISSUE THREAD

**Issue by rolandproud** [OSOceanAcoustics/echopype#522]
Hi, in the latest pip version, roll is both an xarray method and DataArray (e.g. EchoData.platform.roll). This may cause issues - there are easy work arounds but it may be worth changing this.

Cheers,

Roland

**Comment by leewujung** [comment]
@rolandproud : Hmm, the roll is a variable defined in the convention, so we probably don't want to change that. What are the use cases you see can cause issues? Like is someone wants to do `EchoData.platform.roll.roll`?

**Comment by emiliom** [comment]
The existence of `roll` to indicate two different things is unfortunate and indeed potentially confusing; but as @leewujung said, it's not something under our control, since those meanings are external (xarray package and SONAR-netCDF4 convention) and we shouldn't mess with them. At best we can add some notes to the documentation about this potential confusion.

**Comment by rolandproud** [comment]
OK fair enough. Just thought I would point this out in case you could think of a quick and easy fix!

**Comment by leewujung** [comment]
Sounds good! One thing I thought of when seeing this is that there's `range` in the Sv output and the python reserved word `range`. The one in the Sv output probably can be changed to `sonar_range` to make sure it is unique and understandable. 

Thoughts?

**Comment by rolandproud** [comment]
Yes I agree - I would not name anything using the built-in function names. (Note that filter and complex are also built-in functions). For functions from other modules, I would suggest using module.function_name.

**Comment by leewujung** [comment]
> For functions from other modules, I would suggest using module.function_name.

This is in general a good practice, but for OO type of methods, that wouldn't work, like in the previous example, `platform.roll` is an xr.DataArray for which `roll` is a method.

My comment above regarding whether to call something `sonar_range` is more along the line of data convention. ;)

**Comment by rolandproud** [comment]
Yep - sorry that was just a general comment not in reference to platform.roll.

**Comment by leewujung** [comment]
Oh I see. Make sense!
