### ISSUE TITLE
💡 Idea: Potentially update echodata object repr to using datatree

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#534]
## Overview

Currently, we have a built in echodata object repr that we maintain ourselves that was copied over from the arviz library (https://arviz-devs.github.io/arviz/). Tom Nicholas is developing https://github.com/TomNicholas/datatree a package for a DataTree type of representation. Which looks like 

![Screenshot from 2022-01-21 09-14-30](https://user-images.githubusercontent.com/17802172/150570602-f317140c-a5bf-4399-99e1-e7c2544ac45f.png)

this may be a better solution to the echodata object repr in terms of maintainability. However, we might lose some of the nice text that explains what each group is from the convention. Right now the datatree library is not quite ready for use, but good to keep watch 😄

**Comment by leewujung** [comment]
Awesome @lsetiawan! Also I didn't know emojis show up in title also! :D

**Comment by leewujung** [comment]
🚀 this is now implemented and merged!
