### ISSUE TITLE
Interpolating gridded, organized CTD data in env_params during calibration

### ISSUE THREAD

**Issue by imranmaj** [OSOceanAcoustics/echopype#562]
Continuation of #381 

In #381, CTD data is interpolated in cases where it is indexed by ping_time or it is indexed by latitude and longitude. We should support a third case where CTD data is indexed by ping_time, latitude, _and_ longitude.

**Comment by leewujung** [comment]
This issue has stalled and since then we've changed how the environment params are taken into for calibration, so I'll close this now.
