### ISSUE TITLE
Populate or fix sonar_software_name and sonar_model for EK60 and maybe other instruments

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#571]
(Originally discussed in https://github.com/OSOceanAcoustics/echopype/issues/210#issuecomment-822642399)

For EK60:

- Populate `Sonar/sonar_software_name` attribute. Right now it's left blank; see [convert/set_groups_ek60.py#L170](https://github.com/OSOceanAcoustics/echopype/blob/dev/echopype/convert/set_groups_ek60.py#L170)
- `Sonar/sonar_model` attribute entry is "ER60". It should be EK60. Currently EK60 `Sonar/sonar_model` is set in [convert/set_groups_ek60.py#L168](https://github.com/OSOceanAcoustics/echopype/blob/dev/echopype/convert/set_groups_ek60.py#L168) as `self.parser_obj.config_datagram['sounder_name']`, so that looks fine, unless the datagram `sounder_name` is parsed incorrectly.

We haven't examined these closely (AFAIK) for EK80, AZFP or other instruments.

These attributes could be examined in parallel with `Sonar/sonar_serial_number`, #212

**Comment by emiliom** [comment]
I don't think I'm the right person for this issue, since I'm not well versed with the raw datagrams.

**Comment by leewujung** [comment]
I assigned both you and me, because I need to consult you on the naming choice of attributes that we will need to create to take care of the things that may not be in the convention.

**Comment by emiliom** [comment]
Ah! Thanks for that clarification. I didn't see that.

**Comment by emiliom** [comment]
ER60 is in fact the name of the Simrad software. eg, see https://support.echoview.com/WebHelp/Reference/File_formats/Simrad_data_files.htm

**Comment by leewujung** [comment]
We decided to review the detailed content of variables _after_ v0.6.0 now that we have the disruptive type of changes in for v0.6.0.

**Comment by emiliom** [comment]
`sonar_model` was already addressed for v0.6.0. See https://github.com/OSOceanAcoustics/echopype/issues/681#issuecomment-1339962902.

In this issue, the only remaining topic is `sonar_software_name`. It may be more convenient to address that question in #681 and close this issue.
