### ISSUE TITLE
Fix flake8 linting issue that causes all the PR's to fail

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#587]
There seem to be flake8 issue in one of the file that is causing the pre-commit to trigger failure. See below.

![Screenshot from 2022-03-15 10-10-29](https://user-images.githubusercontent.com/17802172/158433450-ba3f3538-716d-42b1-9a3e-2e628a930fb2.png)

**Comment by leewujung** [comment]
I couldn't stand the X when fixing the indentation in #583 so just did this one.
I didn't look into if we can configure flake8 such that it skips strings automatically -- seems like it should be possible?  I just put in `#noqa` for these lines like all the other occurrences of the same error we have in the package. These long lines came from #574.

**Comment by leewujung** [comment]
I'll close this since the immediate cause is resolved.
