### ISSUE TITLE
Tracking issue for Sv and MVBS datasets upgrade

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#591]
We need quite a bit of upgrade for Sv and MVBS datasets, and they are dispersed in multiple issues. This one serves as the tracking issue for all of them.

### Missing attributes
- [x] #481 
- [x] #582
- [x] #615
- [x] #576 

### Provenance
- [x] #618
- [x] ~#221~ (defer to v0.6.1)

### Convention compliance
- [x] #516
- [x] #592

**Comment by leewujung** [comment]
I think we can close this issue now. The issues are all addressed. Thanks @emiliom for your detailed and hard work!

**Comment by emiliom** [comment]
Woo-hoo!
