### ISSUE TITLE
Classifier change for 0.6.0

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#607]
Currently the classifier for echopype development status is Alpha.

https://github.com/OSOceanAcoustics/echopype/blob/4b4f85a48d4a3165f381881325b9cd7d22410fb6/setup.cfg#L10-L11

Knowing that this package is now "widely" used by big orgs such as OOI and NOAA, where they are using it in their systems, I think we should bump this to at least Beta or Production/Stable? What do you all think? The various classifiers can be found at: https://pypi.org/classifiers/

**Comment by leewujung** [comment]
I think we can do Beta right now, and once we are well past all the breaking changes we are introducing with v0.6.x, we can move to Production/Stable. Personally I am more comfortable moving to that stage when we can reliably deal with reasonably big files, like those in #489.
