### ISSUE TITLE
Add echopype software and version provenance attributes to Sv and MVBS datasets

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#618]
An easy first step would be to adapt the SONAR-netCDF4 v1 `Provenance` attributes, to be inserted into Sv and MVBS datasets as global attributes. Here's a sample. Instead of "conversion", the prefix might be "calibration" or something more generic ("processing").

From the `Provenance` group of a converted file:
```
conversion_software_name : echopype
conversion_software_version : 0.5.4
conversion_time : 2021-10-29T00:20:18Z
src_filenames : s3://ncei-wcsd-archive/data/raw/Bell_M._Shimada/SH1707/EK60/Summer2017-D20170728-T195219.raw
```

Should this go into version 0.6.0?

(Note: see #620 vis a vis `src_filenames`)

Added from #221: `remove_noise` output should also include provenance on which Sv file was used for calculation and the bin size along range and ping sequence.

**Comment by leewujung** [comment]
> Instead of "calibration", the prefix might be "calibration" or something more generic ("processing").

Somehow "calibration_software_name" feels a bit weird, "processing_software_name" seems more natural?

**Comment by emiliom** [comment]
> Somehow "calibration_software_name" feels a bit weird, "processing_software_name" seems more natural?

I don't know about the weirdness (I was going off the fact that echopype calls the creation of Sv a "calibration"). But I like "processing" better b/c it's more reusable and we could use the attribute names for both Sv and MVBS.

**Comment by leewujung** [comment]
Ok, let's go with using "processing_*" for these attributes then. This is also something that higher processing levels can use.

**Comment by emiliom** [comment]
Just realized that this issue is related to a pretty old issue, #221. Maybe we could fold the `remove_noise` aspect of #221 into this one, then close it?

**Comment by leewujung** [comment]
> Maybe we could fold the remove_noise aspect of https://github.com/OSOceanAcoustics/echopype/issues/221 into this one, then close it?

Sounds good!

**Comment by emiliom** [comment]
#621 closes this issue
