### ISSUE TITLE
Change `src_filenames` string attribute to `source_filenames` list-of-strings variable

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#620]
This kept falling through the cracks. echopype uses `src_filenames` (in the `Provenance` group), and sets it as a string when it's a single file name (ie, from a simple, single raw file conversion). But in the convention its name is `source_filenames` and it's actually defined as a *variable*, not a global attribute. Also, it's a "vector of datafile names that were used ...", not a single string.

In echopype  `src_filenames` is used only in just a couple of places at this time. BTW, one of those places, in `SetGroupsEK60.set_provenance`, seems overly redundant of `SetGroupsBase.set_provenance`

**Comment by leewujung** [comment]
> in the convention its name is source_filenames and it's actually defined as a variable, not a global attribute. Also, it's a "vector of datafile names that were used ...", not a single string.

This is great, thanks for discovering this.
In `combine_echodata` @imranmaj @lsetiawan and I actually arrived at the conclusion to have `src_filenames` as a data variable, and as a vector also. 
https://github.com/OSOceanAcoustics/echopype/blob/185cc1e6f444538a70996578b5006047e2a51565/echopype/echodata/combine.py#L27-L39
so we can now standardize this according to the convention! :D

**Comment by emiliom** [comment]
Closed by #674
