### ISSUE TITLE
Link to netCDF intro goes to 404

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#626]
## Overview

This issue was initially found by @dissagaliyeva in echoshader issue [#32](https://github.com/OSOceanAcoustics/echoshader/issues/32), bug number 1. In the [echopype why docs](https://echopype.readthedocs.io/en/stable/why.html#interoperability) the url to `netCDF4` leads to a 404 webpage. This is problematic for users in trying to figure out what `netCDF4` is. This link needs to be updated.

> echopype contains tools for converting data from various manufacturer-specific formats into a standardized [netCDF](https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_introduction.html) files.

**Comment by emiliom** [comment]
Fixed in #627. Closing.
