### ISSUE TITLE
Make `set_beam` to always return a list

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#639]
Currently I am casting the result of `set_beam` to always become a list of beam groups:
https://github.com/OSOceanAcoustics/echopype/blob/bdadba51e6699894324ebc68a2c2463d98f5267c/echopype/convert/api.py#L455-L459

I think it would be great to make `set_beam` to always return a list to avoid this casting downstream.

**Comment by emiliom** [comment]
I believe the current setup does not impact our ability to push out 0.6.0 as planned. If so, I suggest delaying this to 0.6.1 (ie, move it out of the 0.6.0 Milestone).

**Comment by b-reyes** [comment]
PR #780 addressed this issue.
