### ISSUE TITLE
Revise command line tool using uniform interface

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#66]
Need to update the command line tool now that the convert and model modules have uniform interface for AZFP and EK60 data (#53). 

Specifically, need to change the input optional parameter to accommodate the additional `.XML` needed for AZFP unpacking.

The goal is to be able to do:
- [x] $ echopype_converter -s ek60 path_to_data_files(allow wildcard)
- [x] $ echopype_converter -s azfp -x xml_file path_to_data_files(allow wildcard)

In the above:
- -s/--system   indicate sonar system
- -x/--xml-file   xml file to use to parse azfp data
- issue warning “An XML file is needed for converting AZFL echosounder data” if -s azfp is passed but xml file not specified
- issue warning “The XML file is ignored as it is not needed for converting

**Comment by prarobinson** [comment]
Currently ConvertAZFP expects two arguments: a data file and an xml file. Is the last warning above, “The XML file is ignored as it is not needed for converting", meant to be issued when the user specifies ek60, or is the goal to make xml files optional for azfp data?

**Comment by leewujung** [comment]
Ouch missed the second half of the sentence. It is for if user issued an XML file for unpacking EK60 data.
