### ISSUE TITLE
Memory and storage issue due to convention compliance in v0.6.0

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#684]
This is a reminder that post-v0.6.0 we need to focus our attention on the expansion of memory usage and potentially storage issues due to the addition of specific dimensions like `ping_time` and `beam` in order to enhance compliance of echopype-generated dataset to the SONAR-netCDF4 convention. In many cases this involves duplication of the original single values from the instrument-generated data files.

#### Summary of these changes from #520:
- EK60: https://github.com/OSOceanAcoustics/echopype/issues/520#issuecomment-1103256165
- EK80: 
  - main decisions: https://github.com/OSOceanAcoustics/echopype/issues/520#issuecomment-1104484705
  - some follow up on the beamwidth variables: https://github.com/OSOceanAcoustics/echopype/issues/679#issuecomment-1126834543 
- AZFP: https://github.com/OSOceanAcoustics/echopype/issues/520#issuecomment-1106620198

#### Initial investigation on storage volume change and observations/things to follow up on:
- https://github.com/OSOceanAcoustics/echopype/pull/680#issuecomment-1127898451
- https://github.com/OSOceanAcoustics/echopype/issues/679#issuecomment-1127908393

**Comment by leewujung** [comment]
@emiliom : I am finding the additional `beam` dimension pretty problematic:
- very inefficient: for EK80 splitbeam data the volume is artificially inflated by 3x-4x because of the way we interpreted the convention
- misleading: because many of the parameters we added the `beam` dimension to actually do not vary across `ping_time` or `beam` and are properties of the transducers
- messy in code: when working on refactoring the calibration code (#904) I had to track down why there was this additional `beam` dimension attached to the calibrated Sv/TS data that needs to be dropped -- I think this is hurting our code readability

I think we should review this decision and see if we can have a "slim" version that departs from the v1 convention but is better all around for the purpose of echopype.

**Comment by emiliom** [comment]
Let's discuss it tomorrow at the hack day

**Comment by leewujung** [comment]
A note while working on split-beam angle addition: all angle computation functions (eg `split_beam_angle.py::get_angle_*`) now has an extra `beam` dimension that gets dropped at the end.

**Comment by leewujung** [comment]
This can be closed now that we've removed the `beam` dimension in cases where it is not needed.
