### ISSUE TITLE
Transfer issues over from OWH/echopype repo

### ISSUE THREAD

**Issue by erinann** [OSOceanAcoustics/echopype#7]
When echopype repo was transferred from OWH2018 the issues did not come with it. They need to be manually transferred over and checked against the current issues. I also need to figure out how I can assign myself the issue.

**Comment by bnwkeys** [comment]
I don't know of any easy way to migrate issues.  From googling around I don't think the github API has that feature explicitly.  Easiest might be manual copy/paste.  There is also [this python tool](https://github.com/IQAndreas/github-issues-import) somebody wrote to do exactly this thing, but considering how few issues we had it might be more hassle than its worth to figure it out.

**Comment by erinann** [comment]
Thanks @bnwkeys. Yep, it's an issue (HA!) with github that Wu-Jung, Valentina, and I ran into over the weekend. Since there aren't that many issues, I'll do the manual copy/paste.
