### ISSUE TITLE
Remnant, messy use of old_* and new_* variables in echodata/combine.py

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#705]
In [echodata/combine.py](https://github.com/OSOceanAcoustics/echopype/blob/dev/echopype/echodata/combine.py), specifically in [combine_echodata()](https://github.com/OSOceanAcoustics/echopype/blob/dev/echopype/echodata/combine.py#L75) and [check_and_correct_reversed_time()](https://github.com/OSOceanAcoustics/echopype/blob/dev/echopype/echodata/combine.py#L34), there's what appears to be remnant unnecessary messiness that should be revisited. Here's a recent exchange describing it:

(@emiliom) Why do all these `old_*` and `new_*` variables need to be declared? I see that in `check_and_correct_reversed_time`, `old_time` is tested for `None`. But as far as I can see, the `old_time` value passed to that function will always be `None`, at this time. Same for `new_time`: the value passed to `check_and_correct_reversed_time` seems like it's always `None` at this time. The function arguments `old_time` and `new_time` could be changed from positional to keyword arguments with default `None` values; or removed altogether, but then you'd have tweak the function code itself.

(@b-reyes) From my understanding the code right now basically uses `old_*` and `new_*` as flags. You are right that how it is done does not make too much sense and we could probably create a better solution to this.

**Comment by b-reyes** [comment]
This issue has been addressed via PR #797, I will go ahead and close it.
