### ISSUE TITLE
Add utility function for swapping channel coordinate with frequency_nominal

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#710]
When there are no duplicate frequencies, replacing the new (0.6.0) `channel` coordinate with the new `frequency_nominal` is a really helpful step (eg, see the [Echopype tour notebook](https://osoceanacoustics.github.io/echopype-examples/echopype_tour.html#compute-mean-volume-backscattering-strength-text-mvbs-and-plot-interactive-echograms-using-hvplot) in echopype-examples)). The steps are brief, but likely hard to figure out for xarray non-experts. Let's create a small utility function that does this. The core will look like this:

```python
def swap_chan(ds: xr.Dataset) -> xr.Dataset:
    """ Function to replace the channel dimension and coordinate with the 
        frequency_nominal variable containing actual frequency values. 
        Note that this step is possible only because there are 
        no duplicated frequencies present.
    """
    return (
        ds
        .set_coords('frequency_nominal')
        .swap_dims({"channel": "frequency_nominal"})
        .reset_coords('channel')
    )
```

But it should first test for duplicate frequencies and return an error if duplicates are found.

**Comment by leewujung** [comment]
I think this can be closed now. I'll move the function to `preprocess` from `utils` in a separate PR before v0.6.1.
