### ISSUE TITLE
Intermittent bucket error during test runs

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#739]
There has been pretty severe intermittent error related to bucket creation (? I haven't looked very closely) in the latest PRs. From a glance it is of a different cause from those in already documented issues.

One example:
https://github.com/OSOceanAcoustics/echopype/runs/6997551890?check_suite_focus=true#step:16:1703

**Comment by lsetiawan** [comment]
PR #761 fixes this issue. Have been pushed to both `dev` and `main` as hotfixes.

**Comment by leewujung** [comment]
Awesome!! Thanks @lsetiawan! Would appreciate a run-down on what the problems and fixes are!

**Comment by emiliom** [comment]
Thanks for the hard work on this! The first problem sounds like it was a significant burden, so hopefully we'll see noticeable benefits.
