### ISSUE TITLE
Rework MVBS tests

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#756]
Right now our tests for `compute_MVBS` are pretty messy and we can benefit from reworking this for robustness and readability.

A laundry list of the few things I noticed while working on #753 were:
- operations in `_construct_MVBS_toy_data` and `_construct_MVBS_test_data` either are hard to decipher or seem can be simplified. It may be the best to rewrite these.
- factor out common components between `test_compute_MVBS_index_binning` and `test_compute_MVBS` to reduce redundancy and avoid error
- the above work with constructed data
- `test_preprocess_mvbs` runs through the mechanism for real data, we should keep this but consider adding variations of the target echo_range and ping_time binning intervals
- add test for Sv data with different length along the `range_sample` dimension for different channel
- use `np.equal` instead of `np.allclose` when testing computed values
- use `pytest` parameterization to reduce clutter and redundancy
- separate out MVBS-related tests to a separate .py file

**Comment by lsetiawan** [comment]
This may be addressed in #1124
