### ISSUE TITLE
Add unit tests for methods that directly write variables to zarr

### ISSUE THREAD

**Issue by b-reyes** [OSOceanAcoustics/echopype#777]
In PR #774 we added the functionality that allows users to directly write variables with a large memory footprint directly to a temporary zarr store. Currently, we have only applied this new functionality to a couple of files. Although these files produce the expected output, a suite of unit tests need to be completed to ensure this addition is behaving as expected.

**Comment by leewujung** [comment]
I'm pushing this to v0.7.1 since it's related to refactoring parsed2zarr.
