### ISSUE TITLE
Update `combine_echodata` documentation

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#836]
With the awesome changes in #808 and #822, now we need to update the documentation in the following areas:
- [ ] inform users of the new functionality to perform out of core computation to combine a large number of files at once
- [ ] mention that users should give a final path for the resulting zarr file
- [ ] detail the change of how we handle reversed timestamps (`ping_time`, `time1`, etc) -- before we corrected the reversed timestamps as part of the `combine_echodata` operation, but now we _do not_ perform this correction anymore

**Comment by emiliom** [comment]
https://echopype.readthedocs.io/en/stable/open-converted.html#combine-echodata-objects

**Comment by leewujung** [comment]
This is addressed in #854. Closing.
