### ISSUE TITLE
Allow for `pathlib.Path` input in `combine_echodata`

### ISSUE THREAD

**Issue by b-reyes** [OSOceanAcoustics/echopype#841]
Currently we require that the input `zarr_path` in `combine_echodata` is a string. For convenience, we should also let `zarr_path` be of type `pathlib.Path`.

**Comment by leewujung** [comment]
@b-reyes : this seems a small standalone issue that can be taken care of at this point, so I just assigned this to surface this to your radar.

@lsetiawan: also pinging you in case you have suggestions or direct pointers from your other work.

**Comment by leewujung** [comment]
This is now addressed in #879.
