### ISSUE TITLE
Expand set of attributes that can be different across files when using combine_echodata

### ISSUE THREAD

**Issue by emiliom** [OSOceanAcoustics/echopype#882]
Starting with 0.6.3 when `combine_echodata` was overhauled, a strict check of input converted files includes a check on nearly all attributes (global *and* variable attributes?) to verify that they're identical; if they're not, the combine step fails and an error is reported.

For some attributes, specially global attributes, there may be valid reasons why the string attribute values are different in each input file. The one case I've run into is `Top-level.summary`; see [echopype-examples](https://osoceanacoustics.github.io/echopype-examples/echopype_tour.html#read-target-raw-files-directly-from-aws-s3-bucket-and-convert-to-netcdf) for a usage example. `summary` is intended to be like a small abstract and will often have details related to the specific data file. Differences in the `summary` text across combined files shouldn't be a reason for `combine_echodata` to fail. An exception should be added at least for this attribute, but there may be others. 

However, a decision would still need to be made about which input file's attribute value to use when populating the combined echodata object. We could hardwire it to, say, always use the attribute from the most recent input file (the last one). Or put in extra work to provide options like: the first file, the last file, or none and return an empty attribute and let the user manually re-populate the attribute in the combined echodata.

The attribute comparison assessments, including exceptions for `date_created` and `conversion_time`, happen in the `zarr_combine._compare_attrs`:
https://github.com/OSOceanAcoustics/echopype/blob/f92f9a0d8bc9af918de2fe2ece3880bd0d188e8d/echopype/echodata/zarr_combine.py#L136-L139

**Comment by leewujung** [comment]
The core of this issue is now addressed in https://github.com/OSOceanAcoustics/echopype/pull/1042.

The only leftover from this is documented in #1055.
