### ISSUE TITLE
Further improve `compute_MVBS` in computation across ping time and channel

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopype#888]
The efficiency of `compute_MVBS` was enhanced in #878, but the current implement may be inefficient if the data is very large -- although @b-reyes and I agreed that the current implementation is "good enough" for the couple use cases we are considering. Nevertheless, our thoughts are documented below.

### Binned averages across ping time
In #878 the major efficiency bottleneck for computing MVBS is resolved by efficiently distributing the first set of binned averages along `echo_range`. To avoid the dask graph getting too large, these binned averages are computed first before the second set of binned averages are compute along `ping_time`. This means that the outcomes of the first set (`er_means` in the code referenced below) are in-memory:
https://github.com/OSOceanAcoustics/echopype/blob/b0b1490a9081400943ac2606e2e6fd2deb4ae71e/echopype/preprocess/mvbs.py#L391-L393

This has 2 potential problems:
- Memory consumption may be an issue if the Sv data is very large
- The second set of binned averages are computed sequentially so potentially inefficient if the Sv data is very large

There are two possible solutions:
- Create a temporary zarr store to store `er_means` and lazy-load the data back for efficient computation.
- Manually chunk and scatter the in-memory `er_means` data into different workers to compute

### Repeat the same computation across channels
In addition, currently the computation across different channels are also done sequentially: https://github.com/OSOceanAcoustics/echopype/blob/b0b1490a9081400943ac2606e2e6fd2deb4ae71e/echopype/preprocess/mvbs.py#L444
Also something to consider, but if each frequency is already computed efficiently it is likely better to not overdo this.

**Comment by lsetiawan** [comment]
Done in #1124
