### ISSUE TITLE
Enhance offload_to_zarr to make it more user friendly and better 

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#957]
## Overview

Currently this functionality is not very user friendly and not everyone may be familiar with the term `offload_to_zarr`. So we've decided to change this term and improvements can be done.

## Tasks

- [x] #958 
- [x] #959 
- [x] #960

_Originally posted by @lsetiawan in https://github.com/OSOceanAcoustics/echopype/issues/886#issuecomment-1458498205_

**Comment by leewujung** [comment]
Great, thanks for detailing these. 

> At some point we'll have to figure out how to distribute this capability!

Yes, this would take some benchmarking probably to decide if we should consider distributing this, or solving on the data organization side, ie figuring out what are the cases where we may not want to pad NaNs -- I've been thinking about this for the setups that ping sequentially across channels.

**Comment by lsetiawan** [comment]
The actual issue that tracks this work is located in Issue #1179
