### ISSUE TITLE
Rename offload_to_zarr to use_swap to make it more user friendly

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#958]
## Overview

`offload_to_zarr` should be renamed to `use_swap` as it is a more familiar term and users don't really need to know what data format we're using under the hood

There will NOT be a required destination path. `use_swap` will use the local drive and the "spilled" memory data files will be stored in echopype's temp folder in `temp_output`.

**Comment by leewujung** [comment]
This is addressed in #962.
