### ISSUE TITLE
Add distributed functionality for spilled data to swap

### ISSUE THREAD

**Issue by lsetiawan** [OSOceanAcoustics/echopype#960]
## Overview

Currently, `use_swap` doesn't distribute the writing of spilled memory to the local disk (swap). It would be great to have a way to do this in a distributed manner for the case of working in a cloud environment.

**Comment by leewujung** [comment]
This is related to #1070

**Comment by lsetiawan** [comment]
Each distributed worker that `open_raw` with `use_swap=True` will spill to its respective disk space. This is a more preferred way since writing spilled data to `s3` can be very slow and problematic. Closing this as explained in https://github.com/OSOceanAcoustics/echopype/pull/1185#issuecomment-1783621362
